- name: Creating prometheus user group
  group: name="prometheus"
  become: true

- name: Creating prometheus user
  user:
    name: "prometheus"
    group: "prometheus"
    system: yes
    shell: "/sbin/nologin"
    comment: "prometheus nologin User"
    createhome: "no"
    state: present

- name: Install prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.3.2/prometheus-2.3.2.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus file to bin
  copy:
    src: "/tmp/prometheus-2.3.2.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "prometheus"
    group: "prometheus"
    remote_src: yes
    mode: 0755

- name: Delete prometheus tmp folder
  file:
    path: '/tmp/prometheus-2.3.2.linux-amd64'
    state: absent

- name: Creates directory
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "prometheus"
    group: "prometheus"
    mode: 0755

- name: Creates directory
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "prometheus"
    group: "prometheus"
    mode: 0755

- name: config file
  template:
    src: ../../../files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Copy systemd init file
  template:
    src: ../../../files/init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes

